import { filterCurrentList } from './search-helpers'
import { expect, test } from '@playwright/test'
import { installArrangementFixture } from './arrangement-fixture'

test.beforeEach(async ({ page }) => {
  await page.addInitScript(installArrangementFixture)
  await page.goto('/')
})

test('quick plans, focus, reminders and keyboard dismissal share one task flow', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  const row = page.locator('[data-task-id="ordinary"]')
  await expect(page.locator('.today-other')).toContainText('整理项目资料')
  await row.getByRole('button', { name: /^设为今日重点/ }).click()
  await expect(page.locator('.today-focus')).toContainText('整理项目资料')
  await expect(row).toContainText('置顶')
  await row.getByRole('button', { name: /^取消今日重点/ }).click()
  await expect(page.locator('.today-other')).toContainText('整理项目资料')
  await row.getByRole('button', { name: /^安排任务/ }).click()
  const dialog = page.getByRole('dialog', { name: '安排任务' })
  await expect(dialog).toBeFocused()
  await page.keyboard.press('Tab')
  await expect(dialog.getByRole('button', { name: '关闭安排' })).toBeFocused()
  await page.keyboard.press('Shift+Tab')
  await expect(dialog.getByRole('button', { name: /安排到今天并设为重点/ })).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(row.getByRole('button', { name: /^安排任务/ })).toBeFocused()
  await page.locator('summary').filter({ hasText: '今日到期' }).click()
  await page.locator('[data-task-id="due"]').getByRole('button', { name: '安排到今天', exact: true }).click()
  await expect(page.locator('.today-other')).toContainText('提交项目报告')
  expect(await page.evaluate(() => window.todoApi.tasks.list().then(tasks => tasks.find(task => task.id === 'due')))).toMatchObject({ dueTime: '23:59', reminderMinutesBefore: 15 })
  await filterCurrentList(page, '不存在')
  await expect(page.locator('.today-reminders')).toHaveCount(0)
  await filterCurrentList(page, '')
  await page.locator('[data-task-id="focus"]').getByRole('button', { name: '#工作', exact: true }).click()
  await expect(page.locator('.today-other [data-task-id="ordinary"]')).toHaveCount(0)
  await expect(page.locator('[data-task-id="past"]')).toHaveCount(0)
  await page.getByRole('button', { name: '清除', exact: true }).click()
  await page.getByRole('button', { name: /^总计划/ }).click()
  await page.locator('[data-task-id="unplanned"]').getByRole('button', { name: /^安排任务/ }).click()
  await dialog.getByRole('combobox', { name: '安排方式' }).click()
  await page.getByRole('option', { name: '按周安排', exact: true }).click()
  await dialog.getByRole('textbox', { name: '计划日期' }).fill('2027-01-06')
  await expect(dialog).toContainText('2027-01-04～2027-01-10')
  await dialog.getByRole('button', { name: '保存计划' }).click()
  await expect(page.locator('[data-task-id="unplanned"]')).toContainText('2027-01-04～2027-01-10')
  expect(errors).toEqual([])
})

test('week cards and drag both arrange without opening the detail editor', async ({ page }) => {
  await page.getByRole('button', { name: /^本周/ }).click()
  const pending = page.locator('[data-task-id="week"]')
  const lastDay = page.locator('.day-column').last()
  await pending.dragTo(lastDay)
  await expect(lastDay.locator('[data-task-id="week"]')).toHaveCount(1)
  await expect(page.locator('.detail-drawer')).toHaveCount(0)
  await lastDay.locator('[data-task-id="week"]').getByRole('button', { name: /^安排任务/ }).click()
  await page.getByRole('dialog', { name: '安排任务' }).getByRole('button', { name: '本月', exact: true }).click()
  await expect(page.locator('[data-task-id="week"]')).toHaveCount(0)
  await page.getByRole('button', { name: /^本月/ }).click()
  await expect(page.locator('[data-task-id="week"]')).toContainText('月计划')
})
