import { filterCurrentList } from './search-helpers'
import { expect, test } from '@playwright/test'
import { installArrangementFixture } from './arrangement-fixture'
import { installFlowHistoryFixture } from './flow-history-fixture'
test.beforeEach(async ({ page }) => {
  await page.addInitScript(installArrangementFixture)
  await page.addInitScript(installFlowHistoryFixture)
  await page.goto('/')
})
test('journal reads multiple dates, paginates, filters and returns from editing in place', async ({ page }, info) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.getByRole('button', { name: /心流 记录与复盘/ }).click()
  await page.getByRole('tab', { name: '历史记录' }).click()
  await expect(page.locator('.journal-entry')).toHaveCount(30)
  await page.getByRole('button', { name: '筛选', exact: true }).click()
  await page.getByLabel('历史开始日期').fill('2020-01-01')
  await expect(page.getByRole('button', { name: '加载更多', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '加载更多', exact: true }).click()
  await expect(page.locator('.journal-entry')).toHaveCount(45)
  const first = page.locator('.journal-entry').nth(2)
  const second = page.locator('.journal-entry').nth(3)
  await first.getByRole('button', { name: '展开当天记录 ↓', exact: true }).click()
  await second.getByRole('button', { name: '展开当天记录 ↓', exact: true }).click()
  await expect(page.locator('.history-reading')).toHaveCount(2)
  await first.getByRole('button', { name: '编辑这一天' }).click()
  await expect(page.getByRole('button', { name: '保存当日复盘' })).toBeVisible()
  await page.getByRole('button', { name: '← 返回历史记录' }).click()
  await expect(page.locator('.journal-entry')).toHaveCount(45)
  await expect(page.locator('.history-reading')).toHaveCount(2)
  await expect(first.getByRole('button', { name: '编辑这一天' })).toBeInViewport()
  await filterCurrentList(page, '不存在的内容')
  await expect(page.locator('.journal-entry')).toHaveCount(0)
  await expect(page.getByText('这段时间没有符合条件的记录。可以换个日期，或补记往日。')).toBeVisible()
  await filterCurrentList(page, '')
  await expect(page.locator('.journal-entry')).toHaveCount(30)
  await page.getByLabel('有待补思考').check()
  await expect(page.locator('.journal-entry')).toHaveCount(15)
  await page.getByRole('button', { name: '最近 30 天' }).click()
  await expect(page.locator('.journal-entry')).toHaveCount(30)
  await page.locator('.main-content').evaluate(element => { element.scrollTop = 0 })
  await page.screenshot({ path: info.outputPath('journal-light.png') })
  await page.evaluate(() => { document.documentElement.dataset.theme = 'dark' })
  await page.setViewportSize({ width: 900, height: 600 })
  await page.screenshot({ path: info.outputPath('journal-dark-small.png') })
  expect(errors).toEqual([])
})
test('backfills a past video and review without opening a browser', async ({ page }) => {
  await page.getByRole('button', { name: /心流 记录与复盘/ }).click()
  await page.getByRole('button', { name: '补记往日', exact: true }).click()
  await page.getByLabel('补录日期').fill('2020-02-03')
  await page.getByRole('button', { name: '开始补记' }).click()
  await page.getByPlaceholder('https://…', { exact: true }).fill('https://example.com/past')
  await page.getByRole('button', { name: '保存补录', exact: true }).click()
  await expect(page.locator('.video-entry')).toHaveCount(1)
  await expect(page.locator('.flow-notice')).toContainText('已补录到 2020-02-03')
  await page.getByRole('tab', { name: /每日复盘/ }).click()
  await page.getByPlaceholder('哪件事值得肯定？').fill('过去的一次认真阅读')
  await page.getByRole('button', { name: '保存当日复盘' }).click()
  await expect(page.locator('.flow-notice')).toContainText('复盘已保存')
  expect(await page.evaluate(async () => (await window.todoApi.flow.getDay('2020-02-03')).review.didWell)).toBe('过去的一次认真阅读')
})
test('long error is contained and plan menu stays usable inside a small scrolling dialog', async ({ page }, info) => {
  await page.setViewportSize({ width: 900, height: 600 })
  await page.locator('[data-task-id="ordinary"]').getByRole('button', { name: /^安排任务/ }).click()
  const combo = page.getByRole('combobox', { name: '安排方式' })
  await combo.click()
  await expect(page.getByRole('option', { name: '按月安排' })).toBeVisible()
  await page.getByRole('option', { name: '按月安排' }).click()
  await expect(combo).toContainText('按月安排')
  await combo.press('ArrowDown')
  await combo.press('End')
  await combo.press('Enter')
  await expect(combo).toContainText('按日安排')
  await page.getByRole('button', { name: '关闭安排' }).click()
  await page.getByRole('button', { name: '设置', exact: true }).click()
  await page.getByRole('button', { name: '更新与关于', exact: true }).click()
  await page.getByText('查看技术详情', { exact: true }).click()
  const details = page.getByLabel('更新错误技术详情')
  expect(await details.evaluate(element => element.clientHeight <= 180 && element.scrollHeight > element.clientHeight && element.scrollWidth <= element.clientWidth)).toBe(true)
  await details.evaluate(element => { element.scrollTop = element.scrollHeight })
  expect(await details.evaluate(element => element.scrollTop)).toBeGreaterThan(0)
  await page.screenshot({ path: info.outputPath('update-error-scroll.png') })
})
