import { expect, test } from '@playwright/test'
import { installArrangementFixture } from './arrangement-fixture'
import { filterCurrentList } from './search-helpers'

test.beforeEach(async ({ page }) => { await page.addInitScript(installArrangementFixture); await page.goto('/') })

test('one search entry supports cancellation, application and clearing without mutating selection prematurely', async ({ page }) => {
  await expect(page.getByRole('button', { name: '历史搜索', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: '选择任务', exact: true }).click()
  await page.getByRole('checkbox', { name: '选择任务 整理项目资料' }).check()
  await page.keyboard.press('Control+k')
  await expect(page.getByRole('searchbox', { name: '搜索关键词' })).toBeFocused()
  await page.getByRole('button', { name: /^当前列表 ·/ }).click()
  await page.getByRole('searchbox', { name: '搜索关键词' }).fill('不存在')
  await page.keyboard.press('Escape')
  await expect(page.getByRole('region', { name: '批量操作' })).toContainText('已选 1 项')
  await filterCurrentList(page, '不存在')
  await expect(page.locator('.task-row')).toHaveCount(0)
  await expect(page.getByRole('region', { name: '批量操作' })).toHaveCount(0)
  await page.getByRole('button', { name: '清除关键词筛选' }).click()
  await expect(page.locator('.task-row').first()).toBeVisible()
  await page.getByRole('button', { name: '标签管理', exact: true }).click()
  await page.keyboard.press('Control+k')
  await expect(page.getByRole('button', { name: /^当前列表 ·/ })).toHaveCount(0)
})

test('detail expansion preserves editing and the menu has four discoverable actions', async ({ page }, info) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  const row = page.locator('[data-task-id="ordinary"]')
  await row.getByRole('button', { name: '任务操作', exact: true }).click()
  await expect(page.getByRole('menu')).toBeInViewport()
  expect(await page.getByRole('menu').evaluate(element => element.parentElement === document.body)).toBe(true)
  await expect(page.getByRole('menuitem')).toHaveText(['查看详情', '取消置顶', '重要程度 未设置 ›', '删除任务'])
  await page.getByRole('menuitem', { name: /重要程度/ }).click()
  await expect(page.getByRole('menuitemradio')).toHaveCount(4)
  await expect(page.getByRole('menuitemradio', { name: '高', exact: true })).toBeInViewport()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('menuitem', { name: '查看详情' })).toBeFocused()
  await page.keyboard.press('Enter')
  await expect(page.getByRole('dialog', { name: '任务详情' })).toBeVisible()
  const notes = page.getByPlaceholder('补充背景、思路或参考信息…')
  await notes.fill('展开和收起不丢失输入')
  const editor = page.locator('.task-editor')
  await expect.poll(async () => Math.round((await editor.boundingBox())!.width)).toBe(600)
  await page.getByRole('button', { name: '展开任务详情' }).click()
  await expect.poll(async () => Math.abs((await editor.boundingBox())!.x - (await page.locator('.main-content').boundingBox())!.x)).toBeLessThan(2)
  await expect(notes).toHaveValue('展开和收起不丢失输入')
  await page.screenshot({ path: info.outputPath('detail-expanded-light.png') })
  await page.getByRole('button', { name: '收起任务详情' }).click()
  await page.setViewportSize({ width: 900, height: 600 })
  await page.evaluate(() => { document.documentElement.dataset.theme = 'dark'; document.documentElement.dataset.density = 'compact' })
  await page.getByRole('combobox', { name: '任务重要程度' }).click()
  await page.keyboard.press('Escape')
  await expect(editor).toBeVisible()
  await expect(notes).toHaveValue('展开和收起不丢失输入')
  await expect(page.locator('.editor-save-state')).toBeInViewport()
  const add = await page.getByRole('button', { name: '添加子任务', exact: true }).boundingBox()
  expect(add!.width).toBeGreaterThan(add!.height)
  expect(await page.getByRole('button', { name: '添加子任务', exact: true }).evaluate(element => getComputedStyle(element).whiteSpace)).toBe('nowrap')
  expect(await editor.evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true)
  await page.screenshot({ path: info.outputPath('detail-small-dark.png') })
  await page.locator('.title-input').blur()
  await expect(page.locator('.editor-save-state')).toContainText('保存失败')
  await expect(page.locator('.editor-error')).toContainText('未能保存')
  await expect(notes).toHaveValue('展开和收起不丢失输入')
  expect(errors).toEqual([])
})
